services:
  db:
    image: mysql:8.0
    container_name: idfm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "3307:3306"
    volumes:
      - ./database/idfm_hackaton.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 2s
      retries: 10

  backend:
    image: node:20-alpine
    container_name: idfm_backend
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=db 
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: idfm_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer:latest
    container_name: idfm_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    container_name: idfm_frontend
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${FRONTEND_PORT}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"
    depends_on:
      - backend

volumes:
  mysql_data: